"""
Master Snakefile for running the Hecatomb pipeline on HTCF.

Rachel Rodgers, Sep 2020
""" 

import os
import sys
sys.path.append("./scripts")
sys.path.append("./scripts/snakemake_helpers")

from snakemake_helpers import *

#----- Snakemake Set Up -----#

configfile: "./config/hecatomb_config.yaml"

# Hecatomb DB paths
CONPATH = config["Paths"]["Contaminants"]
HOSTPATH = config["Paths"]["Host"]
BACPATH = config["Paths"]["Bacteria"]
AATARGET = config["Paths"]["TargetMMseqsAA"]
AATARGETCHECK = config["Paths"]["TargetMMseqsAACheck"]
NTTARGET = config["Paths"]["TargetMMseqsNT"]
NTTARGETCHECK = config["Paths"]["TargetMMseqsNTCheck"]

# Data paths
READDIR = config["Paths"]["Reads"]

# File paths
PHAGE = config["DatabaseFiles"]["Phage"]
NCBIACC = config["DatabaseFiles"]["NCBIAccession"] 

# Write out NCBI Accession path to be read in by R scripts
ncbiAccPath = open("./results/taxonomizr_ncbi_accession_path.txt", "w")
ncbiAccPath.write(NCBIACC)
ncbiAccPath.close()

# Java memory
XMX = config["System"]["Memory"]

# Tools
BBTOOLS = config["Tools"]["BBTools"]
R = config["Tools"]["R"]
SEQKIT = config["Tools"]["Seqkit"]
PULLSEQ = config["Tools"]["Pullseq"]
MMSEQS = config["Tools"]["MMseqs"]

#----- Rename input files if there are any to rename -----#

rename_files(config)

#----- Collect the Input Files -----#

# Pull sample names from the renamed R1 files in /data/renamed/ and store in a list
SAMPLES, = glob_wildcards(os.path.join(READDIR, "renamed", "{sample}_R1.fastq.gz"))

PATTERN_R1 = "{sample}_R1"
PATTERN_R2 = "{sample}_R2"

#----- Snakemake Workflow -----# 

#----- Contaminant Removal -----#
include: "./rules/contaminant_removal.smk"

#----- Cluster Count -----#
include: "./rules/cluster_count.smk"

#----- Merge Sequencing Tables -----#
include: "./rules/seqtable_merge.smk"

#----- MMSeqs2 Query Sequencing Table Against UniProt Viral Proteins Clustered at 99% (Virus Uniprot)-----#
# Extract phage (phage_tax_table.tsv), non-phage (viruses_seqs.fasta), and unclassified (pviral_aa_unclassified_seqs.fasta)
include: "./rules/mmseqs_pviral_aa.smk"

#----- MMSeqs2 Query Probable Viral Non-Phage Sequences (viruses_seqs.fasta) Against UniClust30 ProteinDB (Remove False Positives; Uni Plus Virus)-----#
include: "./rules/mmseqs_pviral_aa_check.smk"

#----- MMSeqs2 Query Probable Viral Unclassified Sequences (pviral_aa_unclassified_seqs.fasta) Against Refseq Virus NT UniVec Masked -----#
include: "./rules/mmseqs_pviral_nt.smk"

#----- Annotate Probable Viral Unclassified Sequences Search (Alignment) Results -----#
include: "./rules/mmseqs_pviral_nt_annotate.smk"

#----- MMSeqs2 Query Probable Non-Phage Viral Sequences Against UniClust30 + Virus UniProt ProteinDB (Remove False Positives) -----#
include: "./rules/mmseqs_pviral_nt_check.smk"

#----- Annotate Probable Viral Non-Phage Sequences Search (Alignment) Results -----#
include: "./rules/mmseqs_pviral_nt_check_annotate.smk"

#----- Concatenate Results -----#
include: "./rules/concatenate_results.smk"

rule all:
	input:
		os.path.join("results", "results", "mmseqs_aa_out", "phage_tax_table.tsv"),
		os.path.join("results", "results", "mmseqs_aa_out", "aln.m8"),
		os.path.join("results", "results", "mmseqs_aa_checked_out", "aln.m8"),
		os.path.join("results", "results", "mmseqs_aa_checked_out", "taxonomyResult.tsv"),
		os.path.join("results", "results", "mmseqs_aa_checked_out", "viruses_checked_aa_tax_table.tsv"),
		os.path.join("results", "results", "mmseqs_aa_checked_out", "unclassified_checked_aa_seqs.fasta"),
		os.path.join("results", "results", "mmseqs_nt_checked_out", "phage_nt_seqs.fasta"),
		os.path.join("results", "results", "viruses_tax_table.tsv"),
		os.path.join("results", "results", "phage_tax_table.tsv"),
		os.path.join("results", "results", "aa.aln.m8"),
		os.path.join("results", "results", "nt.aln.m8")

rule clean:
	shell:
		"rm -rf ./results/"
