#----- Contig Annotation -----#

# Use CAT to annotate the contigs generated by MEGAHIT

rule annotate_filter:
	input:
		os.path.join("results", "assembly", "megahit_contigs", "{sample}.mh.contigs.fa")
	output:
		os.path.join("results", "assembly", "megahit_contigs", "annotation", "{sample}_filtered.contigs.fa")
	threads: 4
	shell:
		"""
		module load {SEQKIT}
		seqkit seq \
			{input} \
			-o {output} \
			-m {MIN} \
			-j {threads} 
		"""
rule annotate_contigs:
	input:
		os.path.join("results", "assembly", "megahit_contigs", "annotation", "{sample}_filtered.contigs.fa")
	params:
		prefix = os.path.join("results", "assembly", "megahit_contigs", "annotation", "{sample}")