---
Patterns:
  Read1Identifiers: ["_R1_"]
  Read2Identifiers: ["_R2_"]
  ReadExtensions: [".fastq.gz"]

Paths:
  Reads: data
  Contaminants: /scratch/ref/hecatomb_databases/contaminants
  Host: /scratch/ref/hecatomb_databases/human_masked
  Bacteria: /scratch/ref/hecatomb_databases/bac_giant/unique_species
  TargetMMseqsAA: /scratch/ref/hecatomb_databases/virus_uniprot/targetDB
  TargetMMseqsAACheck: /scratch/ref/hecatomb_databases/uni_plus_virus/targetDB
  TargetMMseqsNT: /scratch/ref/hecatomb_databases/refseq_virus_nt_UniVec_masked/nt.fnaDB
  TargetMMseqsNTCheck: /scratch/ref/hecatomb_databases/bac_virus_masked/nt.fnaDB
  

DatabaseFiles:
  Phage: /scratch/ref/hecatomb_databases/phage_taxonomic_lineages_2020.txt
  NCBIAccession: /scratch/ref/hecatomb_databases/taxonomizr/accessionTaxa.sql

Tools:
  BBTools: bbtools/38.26
  R: r/3.6.3-python-3.6.5-java-11
  Seqkit: seqkit/0.10.1
  Pullseq: pullseq/1.0.2
  MMseqs: mmseqs2/10-6d92c

System:
  # How much memory to allocate to java
  Memory: -Xmx250g
