---
Patterns:
  Read1Identifiers: ["_R1"]
  Read2Identifiers: ["_R2"]
  ReadExtensions: [".fastq.gz"]

Paths:
  Reads: data/fecal_tx_subset
  Contaminants: /ref/lhlab/data/hecatomb_databases/contaminants
  Host: /ref/lhlab/data/hecatomb_databases/mouse
  Bacteria: /ref/lhlab/data/hecatomb_databases/bac_giant/unique_species
  TargetMMseqsAA: /ref/lhlab/data/hecatomb_databases/virus_uniprot/targetDB
  TargetMMseqsAACheck: /ref/lhlab/data/hecatomb_databases/uni_plus_virus/targetDB
  TargetMMseqsNT: /ref/lhlab/data/hecatomb_databases/refseq_virus_nt_UniVec_masked/nt.fnaDB
  TargetMMseqsNTCheck: /ref/lhlab/data/hecatomb_databases/bac_virus_masked/nt.fnaDB
  

DatabaseFiles:
  Phage: /ref/lhlab/data/hecatomb_databases/phage_taxonomic_lineages_2020.txt
  NCBIAccession: /ref/lhlab/data/hecatomb_databases/taxonomizr/accessionTaxa.sql

Tools:
  BBTools: /ref/mtblab/software/bbmap_38.96/bbmap/
  R: eval $( spack load --sh r@4.2.2 )
  Seqkit: eval $( spack load --sh seqkit@0.10.1 )
  Pullseq: /ref/mtblab/software/pullseq
  MMseqs: /ref/mtblab/software/mmseqs/bin/mmseqs

System:
  # How much memory to allocate to java
  Memory: -Xmx96g
