---
Patterns:
  Read1Identifiers: ["_R1_"]
  Read2Identifiers: ["_R2_"]
  ReadExtensions: [".fastq.gz"]

Paths:
  Reads: ../test_subset
  Contaminants: /ref/lhlab/data/hecatomb_databases/contaminants
  Host: /ref/lhlab/data/hecatomb_databases/human_masked
  Bacteria: /ref/lhlab/data/hecatomb_databases/bac_giant/unique_species
  TargetMMseqsAA: /ref/lhlab/data/hecatomb_databases/virus_uniprot/targetDB
  TargetMMseqsAACheck: /ref/lhlab/data/hecatomb_databases/uni_plus_virus/targetDB
  TargetMMseqsNT: /ref/lhlab/data/hecatomb_databases/refseq_virus_nt_UniVec_masked/nt.fnaDB
  TargetMMseqsNTCheck: /ref/lhlab/data/hecatomb_databases/bac_virus_masked/nt.fnaDB
  

DatabaseFiles:
  Phage: /ref/lhlab/data/hecatomb_databases/phage_taxonomic_lineages_2020.txt
  NCBIAccession: /ref/lhlab/data/hecatomb_databases/taxonomizr/accessionTaxa.sql

Tools:
  BBTools: /ref/lhlab/software/bbmap_38.96/bbmap/
  R: r/3.6.3-python-3.6.5-java-11
  Seqkit: seqkit/0.10.1
  Pullseq: pullseq/1.0.2
  MMseqs: mmseqs2/10-6d92c

System:
  # How much memory to allocate to java
  Memory: -Xmx148g
